-- ========================
-- CLEAN DATABASE
-- ========================
-- Drop tables (reverse dependency order)
DROP TABLE IF EXISTS "Venta_Producto" CASCADE;
DROP TABLE IF EXISTS "Movimiento" CASCADE;
DROP TABLE IF EXISTS "Consulta_Insumo" CASCADE;
DROP TABLE IF EXISTS "Movimiento_Insumo" CASCADE;
DROP TABLE IF EXISTS "Insumo" CASCADE;
DROP TABLE IF EXISTS "Caja_Movimiento" CASCADE;
DROP TABLE IF EXISTS "Caja" CASCADE;
DROP TABLE IF EXISTS "Pago" CASCADE;
DROP TABLE IF EXISTS "Consulta_Servicio" CASCADE;
DROP TABLE IF EXISTS "Servicio" CASCADE;
DROP TABLE IF EXISTS "Consulta" CASCADE;
DROP TABLE IF EXISTS "Veterinario" CASCADE;
DROP TABLE IF EXISTS "Relacion_Dueno_Mascota" CASCADE;
DROP TABLE IF EXISTS "Mascota" CASCADE;
DROP TABLE IF EXISTS "Dueno_Facturacion" CASCADE;
DROP TABLE IF EXISTS "Dueno" CASCADE;
DROP TABLE IF EXISTS "Producto" CASCADE;

-- Drop enums
DROP TYPE IF EXISTS "TipoMovimientoGeneral" CASCADE;
DROP TYPE IF EXISTS "TipoMovimientoInsumo" CASCADE;
DROP TYPE IF EXISTS "TipoMovimiento" CASCADE;
DROP TYPE IF EXISTS "SexoMascota" CASCADE;
DROP TYPE IF EXISTS "EstadoConsulta" CASCADE;
DROP TYPE IF EXISTS "TipoPersona" CASCADE;
DROP TYPE IF EXISTS "EstadoPago" CASCADE;
DROP TYPE IF EXISTS "MetodoPago" CASCADE;
DROP TYPE IF EXISTS "RolDueno" CASCADE;

-- ========================
-- CREATE ENUMS
-- ========================
CREATE TYPE "RolDueno" AS ENUM ('principal', 'acreditado');
CREATE TYPE "MetodoPago" AS ENUM ('efectivo', 'tarjeta', 'transferencia', 'cheque', 'deposito');
CREATE TYPE "EstadoPago" AS ENUM ('pendiente', 'pagado', 'cancelado');
CREATE TYPE "TipoPersona" AS ENUM ('fisica', 'moral');
CREATE TYPE "EstadoConsulta" AS ENUM ('programada', 'en_proceso', 'finalizada', 'cancelada');
CREATE TYPE "SexoMascota" AS ENUM ('Macho', 'Hembra');
CREATE TYPE "TipoMovimiento" AS ENUM ('Ingreso', 'Egreso');
CREATE TYPE "TipoMovimientoInsumo" AS ENUM ('Entrada', 'Salida');
CREATE TYPE "TipoMovimientoGeneral" AS ENUM (
  'caja_ingreso',
  'caja_egreso',
  'insumo_entrada',
  'insumo_salida',
  'venta_producto',
  'pago_consulta',
  'devolucion',
  'ajuste_inventario'
);

-- ========================
-- CREATE TABLES
-- ========================

CREATE TABLE "Dueno" (
  "id_dueno" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nombre_completo" varchar(150) NOT NULL,
  "telefono" varchar(30),
  "correo" varchar(150),
  "direccion" varchar(255),
  "fecha_registro" TIMESTAMP DEFAULT NULL,
  "activo" bool DEFAULT true
);

CREATE TABLE "Dueno_Facturacion" (
  "id_facturacion" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_dueno" int NOT NULL,
  "rfc" varchar(13) NOT NULL,
  "razon_social" varchar(180) NOT NULL,
  "tipo_persona" "TipoPersona" NOT NULL,
  "regimen_fiscal" varchar(100) NOT NULL,
  "uso_cfdi" varchar(50) NOT NULL,
  FOREIGN KEY ("id_dueno") REFERENCES "Dueno" ("id_dueno")
);

CREATE TABLE "Mascota" (
  "id_mascota" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nombre" varchar(100) NOT NULL,
  "especie" varchar(50) NOT NULL,
  "raza" varchar(100),
  "fecha_nacimiento" date,
  "sexo" "SexoMascota",
  "color" varchar(50),
  "senias_particulares" text
);

CREATE TABLE "Relacion_Dueno_Mascota" (
  "id_relacion" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_dueno" int NOT NULL,
  "id_mascota" int NOT NULL,
  "rol" "RolDueno" NOT NULL,
  FOREIGN KEY ("id_dueno") REFERENCES "Dueno" ("id_dueno"),
  FOREIGN KEY ("id_mascota") REFERENCES "Mascota" ("id_mascota")
);

CREATE TABLE "Veterinario" (
  "id_veterinario" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nombre_completo" varchar(150) NOT NULL,
  "cedula" varchar(50) UNIQUE,
  "especialidad" varchar(100),
  "telefono" varchar(30),
  "correo" varchar(150),
  "activo" bool DEFAULT true
);

CREATE TABLE "Consulta" (
  "id_consulta" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_mascota" int NOT NULL,
  "id_veterinario" int NOT NULL,
  "fecha" TIMESTAMP DEFAULT NULL,
  "motivo" text,
  "diagnostico" text,
  "tratamiento" text,
  "estado" "EstadoConsulta" DEFAULT 'programada',
  "observaciones" text,
  FOREIGN KEY ("id_mascota") REFERENCES "Mascota" ("id_mascota"),
  FOREIGN KEY ("id_veterinario") REFERENCES "Veterinario" ("id_veterinario")
);

CREATE TABLE "Servicio" (
  "id_servicio" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nombre" varchar(150) NOT NULL,
  "descripcion" text,
  "costo" decimal(10,2) NOT NULL,
  "duracion_estimada" int
);

CREATE TABLE "Consulta_Servicio" (
  "id_consulta_servicio" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_consulta" int NOT NULL,
  "id_servicio" int NOT NULL,
  "cantidad" int DEFAULT 1,
  "subtotal" decimal(10,2) NOT NULL,
  FOREIGN KEY ("id_consulta") REFERENCES "Consulta" ("id_consulta"),
  FOREIGN KEY ("id_servicio") REFERENCES "Servicio" ("id_servicio")
);

CREATE TABLE "Pago" (
  "id_pago" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_consulta" int,
  "fecha" TIMESTAMP DEFAULT NULL,
  "monto" decimal(10,2) NOT NULL,
  "metodo" "MetodoPago" NOT NULL,
  "estado" "EstadoPago" DEFAULT 'pendiente',
  FOREIGN KEY ("id_consulta") REFERENCES "Consulta" ("id_consulta")
);

CREATE TABLE "Caja" (
  "id_caja" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "fecha_apertura" TIMESTAMP DEFAULT NULL,
  "fecha_cierre" TIMESTAMP DEFAULT NULL,
  "saldo_inicial" decimal(10,2) NOT NULL,
  "saldo_final" decimal(10,2),
  "observaciones" text
);

CREATE TABLE "Caja_Movimiento" (
  "id_movimiento" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_caja" int NOT NULL,
  "fecha" TIMESTAMP DEFAULT NULL,
  "concepto" varchar(150) NOT NULL,
  "monto" decimal(10,2) NOT NULL,
  "tipo" "TipoMovimiento" NOT NULL,
  FOREIGN KEY ("id_caja") REFERENCES "Caja" ("id_caja")
);

CREATE TABLE "Insumo" (
  "id_insumo" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nombre" varchar(150) NOT NULL,
  "descripcion" text,
  "unidad" varchar(50),
  "cantidad_disponible" int DEFAULT 0,
  "costo_unitario" decimal(10,2),
  "fecha_registro" TIMESTAMP DEFAULT NULL
);

CREATE TABLE "Movimiento_Insumo" (
  "id_movimiento_insumo" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_insumo" int NOT NULL,
  "fecha" TIMESTAMP DEFAULT NULL,
  "cantidad" int NOT NULL,
  "tipo" "TipoMovimientoInsumo" NOT NULL,
  "motivo" text,
  "referencia" varchar(100),
  FOREIGN KEY ("id_insumo") REFERENCES "Insumo" ("id_insumo")
);

CREATE TABLE "Consulta_Insumo" (
  "id_consulta_insumo" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_consulta" int NOT NULL,
  "id_insumo" int NOT NULL,
  "cantidad" int NOT NULL,
  FOREIGN KEY ("id_consulta") REFERENCES "Consulta" ("id_consulta"),
  FOREIGN KEY ("id_insumo") REFERENCES "Insumo" ("id_insumo")
);

CREATE TABLE "Producto" (
  "id_producto" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nombre" varchar(150) NOT NULL,
  "descripcion" text,
  "precio" decimal(10,2) NOT NULL,
  "cantidad_disponible" int DEFAULT 0,
  "categoria" varchar(50),
  "fecha_registro" TIMESTAMP DEFAULT NULL,
  "activo" bool DEFAULT true
);

CREATE TABLE "Venta_Producto" (
  "id_venta" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_producto" int NOT NULL,
  "fecha" TIMESTAMP DEFAULT NULL,
  "cantidad" int NOT NULL,
  "subtotal" decimal(10,2) NOT NULL,
  "id_pago" int,
  FOREIGN KEY ("id_producto") REFERENCES "Producto" ("id_producto"),
  FOREIGN KEY ("id_pago") REFERENCES "Pago" ("id_pago")
);

CREATE TABLE "Movimiento" (
  "id_movimiento" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "fecha" TIMESTAMP DEFAULT NULL,
  "tipo" "TipoMovimientoGeneral" NOT NULL,
  "concepto" varchar(200) NOT NULL,
  "monto" decimal(10,2),
  "cantidad" int,
  "referencia_id" int,
  "referencia_tabla" varchar(50),
  "usuario" varchar(100),
  "observaciones" text,
  "activo" bool DEFAULT true
);
